### PR TITLE
Tweak and improve styling for dummy app page structure and nav

### PR DESCRIPTION
**Pull request by BrianSipple**
This PR makes a few improvements to the overall page structure of the dummy app demo:
- Better semantic markup
  - The logo and title in the navbar aren't part of any actual "nav" menu, so they don't need to be nested in a list
  - The links of the sidenav _are_ part of a nav menu structure, so I made them list items inside of a `<nav>`
  - Using an `<aside>` tag for the sidenav and a `<main>` tag for the main content.
- Making the navbar fixed to the top of the page
  - Scroll is now given at the level of the `<main>` element.
- A few styling utilities to help with the changes mentioned above.

### CODE REVIEW

**Comment by BrianSipple** [comment]
@Ticketfly/frontenders

**Comment by BrianSipple** [comment]
@spencer516 A) nope. B) Percy?

**Comment by spencer516** [comment]
Yea — saw you found what Percy is. Also, I most certainly did not "Request Changes" GITHUB! Gosh.

**Comment by spencer516** [comment]
Also, it looks like you've got some conflicts with master.

**Comment by BrianSipple** [comment]
Ah, yep. I need to learn about `sass-lint` and how we're using it -- one sec 😛.

**Comment by BrianSipple** [comment]
@spencer516 I made a few changes to keep `sass-lint` happy. Since that won't be a factor in `1.x`, I'll save a few of the syntax updates for that effort 😄 .

**Pull request merged**
